version: '2'
services:
    allipmanagerwebview-app:
        image: allipmanagerwebview
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://allipmanagerwebview-mssql:1433;database=allipmanagerwebview
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    allipmanagerwebview-mssql:
        extends:
            file: mssql.yml
            service: allipmanagerwebview-mssql
